config/routes.rb
Rails.application.routes.draw do

  get 'votes/verification', as: "verification"
  post 'votes/verifiee', as: "verifiee"
  get 'votes/validation', as: "validation"
  post 'votes/valider', as: "valider"
  get 'votes/reset', as: "reset"
  get 'admins/sign', as: "sign_admin"
  get 'fokontanies/result', as: "result_fkt"
  get 'communes/result', as: "result_cmn"
  get 'regions/result', as: "result_rg"
  get 'users/sign', as: "sign_user"
  get 'recensements/affiche'
  root 'home#index'
  
  devise_for :admins
  devise_for :users

  resources :daties
  resources :regions do 
    resources :communes
  end 
  resources :communes,only: [:destroy]  do
    resources :fokontanies
  end
  resources :fokontanies,only: [:destroy] do
    resources :recensements
  end
  resources :recherches,only: [:index]
  resources :admins
  resources :recensements
  resources :votes, only: [:new]
  resources :candidats do
    resources :votes, except: [:new]
    resources :profils, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
	class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidat.rb
class Candidat < ApplicationRecord

	has_one_attached :profil
 	has_many :votes 

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :fokontanies
  has_many :admins
  has_many :users

end

app/models/daty.rb
class Daty < ApplicationRecord
end

app/models/fokontany.rb
class Fokontany < ApplicationRecord
  belongs_to :commune, optional: true
  has_many :recensements
  has_many :admins
  has_many :users
end

app/models/recensement.rb
class Recensement < ApplicationRecord
  belongs_to :fokontany, optional: true
  has_many :votes
  validates :full_name,
  presence: true

  validates :cin,
  presence: true,
  length: {minimum: 12},
  uniqueness: true

  validates :contact,
  presence: true,
  length: {minimum: 10},
  uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :communes
	has_many :admins
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :recensement
  belongs_to :candidat
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/candidats_helper.rb
module CandidatsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/daties_helper.rb
module DatiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/recherches_helper.rb
module RecherchesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admins/edit.html.erb
<%= form_tag url_for(action:'update'), method:'put' do %>
	<input type="text" name="name" value="<%= @admin.name %>"  placeholder="Nom du responsable"><br>
	<input type="text" name="region_name" <% if @admin.region_id != nil %> value= "<%= @admin.region.name %>" <% end %> placeholder="Region"><br>
	<input type="text" name="commune_name" <% if @admin.commune_id != nil %> value= "<%= @admin.commune.name %>" <% end %> placeholder="Commune"><br>
	<input type="text" name="fokontany_name"  <% if @admin.fokontany_id != nil %> value= "<%= @admin.fokontany.name %>" <% end %> placeholder="Fokontany"><br>
	<input type="text" name="email" value= "<%= @admin.email %>" placeholder="Fokontany@commune.com"><br>
	<input type="password" name="password" value= "<%= @admin.password %>" placeholder="Password"><br>
	<input type="submit" value="sauver"><br>
<%end%>

app/views/admins/index.html.erb
<h1>Liste de tous les admins : </h1>
<%= @admin.each do |admin| %>
	<p>
		Nom et prénom : <%= admin.name %> | <%= admin.region %> | <%= admin.commune %> | <%= admin.fokontany %><br>
	</p>
	<%= link_to Supprimer, admin_path, method:"delete", data:{confirm:"Supprimé?"} %>
<% end %>

app/views/admins/show.html.erb
<h1>A propos du responsable dans le Fokontany : </h1>

<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nom : <%= @admin.name %></li>
    <% if @admin.region_id != nil %>
    	<li class="list-group-item">Region : <%= @admin.region.name %></li>
    <% end %>
    <% if @admin.commune_id != nil %>
    	<li class="list-group-item">Commune : <%= @admin.commune.name %></li>
    <% end %>
    <% if @admin.fokontany_id != nil %>
    	<li class="list-group-item">Fokontany : <%= @admin.fokontany.name %></li>
    <% end %>
    <li class="list-group-item">Email : <%= @admin.email %></li>
  </ul>
<a href="<%= edit_admin_path(@admin.id) %>"><i class="fa fa-edit"></i>Editer</a></div><br><br>
<% if @admin.fokontany_id != nil %>
	<a class="nav-link" href="<%= new_fokontany_recensement_path(@admin.fokontany.id) %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Ajouter une personne</a>
<% end %>

app/views/admins/sign.html.erb
<section class="contenue" id="background-admin">
<p class="titre">Bienvenue dans la page d'administrateur !!!</p>
	<%= link_to "Se connecter", new_admin_session_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sahy Hifidy </title>
    <link rel="icon" href="../images/logo.png" type="image/png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  </head>
  <body> 

    <nav class="navbar navbar-expand-lg  bg-light sticky-top">  
      <a class="nav-link" href="<%= root_path %>"><%= image_tag  "logo.png", class:"logo" %></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% @date = Daty.last %>
          <% if @date != nil %>
            <% if Time.now.to_i <= @date.fin_propagande.to_i %>
              <li class="nav-item active">
                <%= link_to  "Candidats", candidats_path , class:"nav-link"%>
              </li>
            <% end %>
            <% if Time.now.to_i >= @date.debut_vote.to_i && Time.now.to_i <= @date.fin_vote.to_i %>
              <li class="nav-item">
                <a class="nav-link" id="marge" href="<%= verification_path %>">Vote</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Résultat de vote
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<%= result_rg_path %>">Regional</a>
                  <a class="dropdown-item" href="<%= result_cmn_path %>">Communale</a>
                  <a class="dropdown-item" href="<%= result_fkt_path %>">Fokontany</a>
                </div>
              </li>
            <% end %>
          <% end %>
          <li class="nav-item ">
            <a class="nav-link" href="<%= regions_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Region</a>
          </li>
           <li class="nav-item ">
            <a class="nav-link" href="<%= recensements_affiche_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Liste des inscrits</a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item ">
              <a class="nav-link" href="<%= new_daty_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Date</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="<%= new_candidat_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Créer candidat</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="<%= sign_user_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Dashbord</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="<%= destroy_user_session_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false" data-method="delete">Se deconnecter</a>
            </li>
          <% end %>          
          <%  if admin_signed_in?%>
            <li class="nav-item ">
              <a class="nav-link" href="<%= admin_path(current_admin.id) %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">Dashbord</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="<%= destroy_admin_session_path %>" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false" data-method="delete">Se deconnecter</a>
            </li>

          <% end %>
        </ul>
          <%=form_tag recherches_path , class:"form-inline my-2 my-lg-0" ,method:'get' do%>
        <input type="text" class="search form-control mr-sm-2" name="find" placeholder="Search...">
        <input type="submit" class="btn btn-outline-success my-2 my-sm-0">
      <%end%>   
      </div>
    </nav>

    <%= yield %>
  </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/48ba21fe93.js"></script>
      <!-- Animation js -->
    <script src="script.js"></script>
</html>