config/routes.rb
Rails.application.routes.draw do

  get 'votes/verification', as: "verification"
  post 'votes/verifiee', as: "verifiee"
  get 'votes/validation', as: "validation"
  post 'votes/valider', as: "valider"
  get 'votes/reset', as: "reset"
  get 'admins/sign', as: "sign_admin"
  get 'fokontanies/result', as: "result_fkt"
  get 'communes/result', as: "result_cmn"
  get 'regions/result', as: "result_rg"
  get 'users/sign', as: "sign_user"
  get 'recensements/affiche'
  root 'home#index'
  
  devise_for :admins
  devise_for :users

  resources :daties
  resources :regions do 
    resources :communes
  end 
  resources :communes,only: [:destroy]  do
    resources :fokontanies
  end
  resources :fokontanies,only: [:destroy] do
    resources :recensements
  end
  resources :recherches,only: [:index]
  resources :admins
  resources :recensements
  resources :votes, only: [:new]
  resources :candidats do
    resources :votes, except: [:new]
    resources :profils, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
	class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidat.rb
class Candidat < ApplicationRecord

	has_one_attached :profil
 	has_many :votes 

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :fokontanies
  has_many :admins
  has_many :users

end

app/models/daty.rb
class Daty < ApplicationRecord
end

app/models/fokontany.rb
class Fokontany < ApplicationRecord
  belongs_to :commune, optional: true
  has_many :recensements
  has_many :admins
  has_many :users
end

app/models/recensement.rb
class Recensement < ApplicationRecord
  belongs_to :fokontany, optional: true
  has_many :votes
  validates :full_name,
  presence: true

  validates :cin,
  presence: true,
  length: {minimum: 12},
  uniqueness: true

  validates :contact,
  presence: true,
  length: {minimum: 10},
  uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :communes
	has_many :admins
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :recensement
  belongs_to :candidat
end

app/controllers/recensements_controller.rb
class RecensementsController < ApplicationController
  before_action :test_signed, only: [:show]
  before_action :testes, except: [:index, :affiche, :initialisation]

  def index
    @fokontany = Fokontany.find_by(id: params[:fokontany_id])

	  @people = @fokontany.recensements
    
  end

  def affiche
    @recensement = Recensement.all.order(full_name: :asc)
  end

  def show
    @recensements = Recensement.find(params[:id])
    @fokontany = Fokontany.find_by(id: params[:fokontany_id])
    # @recensement = Fokontany.find(id: @recensements.fokontany_id)
  end

  def new
    @admin = Admin.find_by(id: params[:id])
    @recensement = Recensement.new
  end

  def create
    @fokontany = Fokontany.find(params[:fokontany_id])
    @recensement = Recensement.all
    @recensement.each do |recensement|
      if recensement.cin == params[:cin]
        flash[:danger] = "Habitant déjà éxisté"
        render "new"
        break
      end
    end
    
  	@recensement = Recensement.new(full_name: params[:full_name], cin: params[:cin],
      pere: params[:nom_pere], mere: params[:nom_mere], logement: params[:logement],
      travail: params[:travail], contact: params[:contact], fokontany: @fokontany)
  	if @recensement.save
  		redirect_to fokontany_recensements_path(@fokontany.id)
  	else
      render "new"
  	end
  end

  def edit
    @recensement = Recensement.find(params[:id])
  end

  def update
  	@recensement = Recensement.update(full_name: params[:full_name], cin: params[:cin],
      pere: params[:nom_pere], mere: params[:nom_mere], logement: params[:logement],
      travail: params[:travail], contact: params[:contact], fokontany: current_admin.fokontany)
  	if @recensement.save
  		redirect_to "/recensements"
  	else
  		render "edit"
  	end
  end

  def destroy
  	@recensement = Recensement.find(params[:id])
    @recensement.destroy
    redirect_to root_path
  end
  private
  def testes
    @recensements = Recensement.find_by(id: params[:id])
    if admin_signed_in?
      if current_admin.fokontany.name == @recensement.fokontany.name
        return true
      else
        redirect_to root_path
      end
    end
  end

  def test_signed
    if admin_signed_in?
      return true
    elsif user_signed_in?
      return true
    else
      redirect_to root_path
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def search
        @recensement = Recensement.all

        @q = recensements.search(params[:q])
        @people = @q.result 
    end
end

app/helpers/candidats_helper.rb
module CandidatsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/daties_helper.rb
module DatiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/recensements_helper.rb
module RecensementsHelper
end

app/helpers/recherches_helper.rb
module RecherchesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/recensements/affiche.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nom et Prénons</th>
      <th scope="col">CIN</th>
      <% if user_signed_in? %>
        <th scope="col">Télephone</th>
        <th scope="col">Information</th> 
      <% end %>
    </tr>
  </thead>
    <% i = 0 %>
  <% @recensement.each do |recensement| %>
  <tbody class="table-1">
    <tr>
      <th scope="row"><%= i += 1%></th>
      <td><%= recensement.full_name %></td>
      <td><%= recensement.cin %></td>
      <% if user_signed_in? || admin_signed_in?%>
        <td><%= recensement.contact %></td>
        <td><a href="/recensements/<%=recensement.id%>" > Voir </a></td>
      <% end %>
    </tr>
    <% end %> 
  </tbody>
</table>

app/views/recensements/edit.html.erb
<div class="container">
	<%= form_tag url_for(action:'create'), method:"post" do %>
	    <form class="form-signin">
	  <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
	  <h1 class="h3 mb-3 font-weight-normal"> information </h1>
	  Nom Complet 
	  <input type="text" class="form-control" value="<%= @recensement.full_name %>" name="full_name"><br>
	  CIN
	  <input type="text" class="form-control" value="<%= @recensement.cin %>" name="cin"><br>
	  Nom du père
	  <input type="text" class="form-control" value="<%= @recensement.pere %>" name="nom_pere"><br>
	  Nom de la mère
	  <input type="text" class="form-control" value="<%= @recensement.mere %>" name="nom_mere"><br>
	  Logement
	  <input type="text" class="form-control" value="<%= @recensement.logement %>" name="logement"><br>
	  Travail
	  <input type="text" class="form-control" value="<%= @recensement.travail %>" name="travail"><br>
	  Contact
	  <input type="text" class="form-control" value="<%= @recensement.contact %>" name="contact"><br>

	  <button class="btn btn-lg btn-primary btn-block" type="submit"> Sauvegarder </button>
	  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
	</form>
	<% end %>
</div>

app/views/recensements/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Numéro</th>
      <th scope="col">Nom et Prénons</th>
      <th scope="col">CIN</th>
      <% if admin_signed_in? %>
        <th scope="col">Télephone</th>
        <th scope="col">Supprimer</th>
      <% end %>
    </tr>
  </thead>
    <% i = 0 %>
  <% @people.each do |recensement| %>
  <tbody class="table-1">
    <tr>
      <th scope="row"><%= i += 1%></th>
      <% if admin_signed_in? %>
        <td><%= link_to recensement.full_name, fokontany_recensement_path(@fokontany.id, recensement.id) %></td>
      <% else %>
        <td><%= recensement.full_name %></td>
      <% end %>
      <td><%= recensement.cin %></td>
      <% if admin_signed_in? %>
        <td><%= recensement.contact %></td>
        <td><i><%= link_to 'Supprimer', recensement_path(recensement.id), style:"color: red", data:{confirm:"Supprimé?"} %></i></td>
      <% end %>
    </tr>
    <% end %> 
  </tbody>
</table>

app/views/recensements/new.html.erb
<div class="container">
  <%= form_tag url_for(action:'create'), method:"post" do %>
      <form class="form-signin">
    <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal"> information </h1>
    Nom Complet 
    <input type="text" class="form-control" placeholder="Nom complet" name="full_name"><br>
    CIN
    <input type="text" class="form-control" placeholder="CIN" name="cin"><br>
    Nom du père
    <input type="text" class="form-control" placeholder="Père" name="nom_pere"><br>
    Nom de la mère
    <input type="text" class="form-control" placeholder="Mère" name="nom_mere"><br>
    Logement
    <input type="text" class="form-control" placeholder="Logement" name="logement"><br>
    Travail
    <input type="text" class="form-control" placeholder="Travail" name="travail"><br>
    Contact
    <input type="text" class="form-control" placeholder="0 3 . . . . . . 5 5" name="contact"><br>

    <button class="btn btn-lg btn-primary btn-block" type="submit"> Créer </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
  </form>
  <% end %>
</div>

app/views/recensements/show.html.erb
<h1>A propos de notre electeur : </h1>

<div class="card">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nom : <%= @recensements.full_name %></li>
    <li class="list-group-item">CIN : <%= @recensements.cin %></li>
    <li class="list-group-item">Nom du père : <%= @recensements.pere %></li>
    <li class="list-group-item">Nom de la mère : <%= @recensements.mere %></li>
    <li class="list-group-item">Logement : <%= @recensements.logement %></li>
    <li class="list-group-item">Profession : <%= @recensements.travail %></li>
    <li class="list-group-item">Contact : <%= @recensements.contact %></li>
  </ul>
<a href="/recensements/<%=@recensements.id%>" data-method="delete"><i class="fa fa-trash"></i></a></div>