config/routes.rb
Rails.application.routes.draw do

  get 'votes/verification', as: "verification"
  post 'votes/verifiee', as: "verifiee"
  get 'votes/validation', as: "validation"
  post 'votes/valider', as: "valider"
  get 'votes/reset', as: "reset"
  get 'admins/sign', as: "sign_admin"
  get 'fokontanies/result', as: "result_fkt"
  get 'communes/result', as: "result_cmn"
  get 'regions/result', as: "result_rg"
  get 'users/sign', as: "sign_user"
  get 'recensements/affiche'
  root 'home#index'
  
  devise_for :admins
  devise_for :users

  resources :daties
  resources :regions do 
    resources :communes
  end 
  resources :communes,only: [:destroy]  do
    resources :fokontanies
  end
  resources :fokontanies,only: [:destroy] do
    resources :recensements
  end
  resources :recherches,only: [:index]
  resources :admins
  resources :recensements
  resources :votes, only: [:new]
  resources :candidats do
    resources :votes, except: [:new]
    resources :profils, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
	class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidat.rb
class Candidat < ApplicationRecord

	has_one_attached :profil
 	has_many :votes 

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  has_many :fokontanies
  has_many :admins
  has_many :users

end

app/models/daty.rb
class Daty < ApplicationRecord
end

app/models/fokontany.rb
class Fokontany < ApplicationRecord
  belongs_to :commune, optional: true
  has_many :recensements
  has_many :admins
  has_many :users
end

app/models/recensement.rb
class Recensement < ApplicationRecord
  belongs_to :fokontany, optional: true
  has_many :votes
  validates :full_name,
  presence: true

  validates :cin,
  presence: true,
  length: {minimum: 12},
  uniqueness: true

  validates :contact,
  presence: true,
  length: {minimum: 10},
  uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :communes
	has_many :admins
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :region, optional: true
  belongs_to :commune, optional: true
  belongs_to :fokontany, optional: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :recensement
  belongs_to :candidat
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
	before_action :authenticate_user!,only: [:destroy]
	before_action :test_user,only: [:destroy]

	def index
		@region = Region.all
	end
	def result 
		@region = Region.all
	end
	def destroy
		@region = Region.find(id: params[:id])
		@commune = @region.communes.all
		@commune.each do |commune|
			@fokontany = commune.fokontanies.all
			@fokontany.each do |fokontany|
				fokontany.recensements.destroy_all
			end
			commune.fokontanies.dest
		end
		@commune.destroy
		@region.destroy
	end
	private
	def test_user
	    @user = User.all
	    val = 0
	    @user.each do |user|
	      if current_user == user
	        val = 1
	        break
	      else
	        val = 0
	      end
	    end
	    if val == 1
	      return true
	    else
	      redirect_to root_path
	    end   
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def search
        @recensement = Recensement.all

        @q = recensements.search(params[:q])
        @people = @q.result 
    end
end

app/helpers/candidats_helper.rb
module CandidatsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/daties_helper.rb
module DatiesHelper
end

app/helpers/fokontanies_helper.rb
module FokontaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/recherches_helper.rb
module RecherchesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/regions/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Liste de toutes les régions :</h1>
</div>

<% @region.each do |region| %>
  <div class="container">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <%= link_to region.name, region_communes_path(region.id) %>
        </div>
        <% if user_signed_in? %>
        	<%= link_to 'Supprimer', region_path(region.id), :class => "btn btn-danger", data:{confirm:"Supprimé?"} %>
        <% end %>
      </div>
    </div>
  </div>
<% end %> 

app/views/regions/result.html.erb
<% @region.each do |region| %>
    <% k=0 %> 
  <ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= region.name %>
        <% region.communes.each do |commune|%>   
          <% commune.name %> 
            <% commune.fokontanies.each do |fokontany| %>
              <% fokontany.recensements.each do |recensement|%>
          <% k += recensement.votes.count %>     
              <% end %>      
            <% end %>
        <% end %>
          <span class="badge badge-primary badge-pill"><%= k %></span>
    </li>
  </ul>
<% end %>

		



       
      



         

 









  

app/views/regions/showdelet.html.erb
<% @region.each do |region| %>
	<%= region.name %><br>
	<%= link_to 'Supprimer', region_path(region.id), method:"delete", data:{confirm:"Supprimé?"} %>

<% end %>